
name: Run Tests  # Обязательное поле "name" в начале файла

on: [push]  # Триггеры должны идти после имени

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # "uses" теперь внутри блока steps
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install chromium-driver
        
    - name: Run tests
      run: pytest tests/ --alluredir=reports
      
    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: reports
